schemes:
  - id: "hdfc-mid-cap"
    name: "HDFC Mid-Cap Opportunities Fund"
    url: "https://groww.in/mutual-funds/hdfc-mid-cap-fund-direct-growth"
    category: "Equity"
  - id: "hdfc-large-cap"
    name: "HDFC Top 100 Fund"
    url: "https://groww.in/mutual-funds/hdfc-large-cap-fund-direct-growth"
    category: "Equity"
  - id: "hdfc-small-cap"
    name: "HDFC Small Cap Fund"
    url: "https://groww.in/mutual-funds/hdfc-small-cap-fund-direct-growth"
    category: "Equity"
  - id: "hdfc-gold-etf-fof"
    name: "HDFC Gold ETF FOF"
    url: "https://groww.in/mutual-funds/hdfc-gold-etf-fund-of-fund-direct-plan-growth"
    category: "Other"
  - id: "hdfc-defence-fund"
    name: "HDFC Defence Fund"
    url: "https://groww.in/mutual-funds/hdfc-defence-fund-direct-growth"
    category: "Equity"
